development:
  send_notifications: false
  server:             192.168.1.64
  password:           xxx

test:
  send_notifications: false
  server:             192.168.1.64
  password:           xxx

production:
  send_notifications: false
  server:             192.168.1.64
  password:           xxx
